apiVersion: v1
kind: Pod
metadata:
  name: my-mysql-pod
  labels:
    app: mysql
spec:
  containers:
  - name: my-mysql-container
    image: mysql:5.7
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: password
    - name: MYSQL_DATABASE
      value: wordpress
    ports:
    - containerPort: 3306
      protocol: TCP
